apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: infrapilot-route
  namespace: infrapilot
spec:
  to:
    kind: Service
    name: infrapilot-api
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
