# Build Stage
FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/infrapilot-agent ./cmd/agent/main.go

# Execution Stage
FROM alpine:3.19

RUN apk --no-cache add ca-certificates curl procps docker-cli

WORKDIR /app

COPY --from=builder /app/infrapilot-agent /app/infrapilot-agent

ENTRYPOINT ["/app/infrapilot-agent"]
