#!/bin/bash
# ===========================================================
# InfraPilot Enterprise - Cloud Deployment Script
# ===========================================================
# This script deploys InfraPilot to a cloud VM (Ubuntu 22.04+)
# using Docker Compose with production settings.
#
# Prerequisites:
#   - Ubuntu 22.04+ server with SSH access
#   - Docker & Docker Compose installed
#   - Domain name pointing to server (optional)
#   - SSL certificates (optional, for HTTPS)
#
# Usage:
#   chmod +x deploy-cloud.sh
#   ./deploy-cloud.sh [server-ip-or-domain]
#
# Example:
#   ./deploy-cloud.sh 123.456.789.0
#   ./deploy-cloud.sh infrapilot.example.com
# ===========================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

SERVER="${1:-}"
if [ -z "$SERVER" ]; then
    echo -e "${RED}Error: Server IP or domain required${NC}"
    echo "Usage: $0 <server-ip-or-domain>"
    exit 1
fi

echo -e "${CYAN}============================================${NC}"
echo -e "${CYAN}  InfraPilot Enterprise - Cloud Deployment${NC}"
echo -e "${CYAN}============================================${NC}"
echo ""
echo -e "${YELLOW}Deploying to:${NC} $SERVER"
echo ""

# ---- Configuration ----
SSH_USER="${SSH_USER:-ubuntu}"
DEPLOY_DIR="${DEPLOY_DIR:-/opt/infrapilot}"
DOMAIN="${SERVER}"  # Use server IP/domain as default
LETSENCRYPT_EMAIL="${LETSENCRYPT_EMAIL:-admin@${DOMAIN}}"
JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 32)}"
ENROLLMENT_KEY="${ENROLLMENT_KEY:-$(openssl rand -hex 16)}"
DB_PASSWORD="${DB_PASSWORD:-$(openssl rand -hex 20)}"
REDIS_PASSWORD="${REDIS_PASSWORD:-$(openssl rand -hex 20)}"
API_ENCRYPTION_KEY="${API_ENCRYPTION_KEY:-$(openssl rand -hex 32)}"

echo -e "${GREEN}[1/6]${NC} Checking SSH connection..."
ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 "${SSH_USER}@${SERVER}" "echo 'SSH connection OK'" || {
    echo -e "${RED}Failed to connect to $SERVER${NC}"
    exit 1
}

echo -e "${GREEN}[2/6]${NC} Installing Docker and dependencies..."
ssh "${SSH_USER}@${SERVER}" << 'REMOTE'
    set -e
    # Install Docker if not present
    if ! command -v docker &> /dev/null; then
        curl -fsSL https://get.docker.com | bash
        sudo usermod -aG docker "$USER"
    fi

    # Install Docker Compose if not present
    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null 2>&1; then
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
    fi

    echo "Docker: $(docker --version)"
    echo "Compose: $(docker compose version 2>/dev/null || docker-compose --version)"
REMOTE

echo -e "${GREEN}[3/6]${NC} Creating deployment directory and configuration..."
ssh "${SSH_USER}@${SERVER}" "sudo mkdir -p ${DEPLOY_DIR} && sudo chown -R \$USER:\$USER ${DEPLOY_DIR}"

# Generate .env file
cat > /tmp/infrapilot.env << ENVEOF
# InfraPilot Enterprise - Production Configuration
# Auto-generated by deploy-cloud.sh on $(date)

# Server Configuration
SERVER_PORT=8080
SERVER_MODE=release
LOG_LEVEL=info
LOG_JSON=true

# Database
DB_HOST=postgres
DB_PORT=5432
DB_NAME=infrapilot
DB_USER=infrapilot
DB_PASSWORD=${DB_PASSWORD}
DB_SSLMODE=disable
DB_MAX_OPEN_CONNS=25
DB_MAX_IDLE_CONNS=5
DB_CONN_MAX_LIFETIME=300

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_DB=0

# Authentication
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY=24h
REFRESH_TOKEN_EXPIRY=168h
ENROLLMENT_TOKEN=${ENROLLMENT_KEY}

# Encryption
API_ENCRYPTION_KEY=${API_ENCRYPTION_KEY}

# Worker Configuration
METRIC_WORKERS=10
ALERT_WORKERS=5
LOG_WORKERS=5
DISCOVERY_WORKERS=3
AI_WORKERS=2
INVENTORY_WORKERS=3
QUEUE_BUFFER=1000

# Rate Limiting (requests per minute per IP)
RATE_LIMIT_PER_MINUTE=60

# CORS
CORS_ORIGINS=*

# Domain Configuration
DOMAIN=${DOMAIN}
ENVEOF

scp /tmp/infrapilot.env "${SSH_USER}@${SERVER}:${DEPLOY_DIR}/.env"

echo -e "${GREEN}[4/6]${NC} Copying Docker Compose and config files..."
# Create docker-compose.yml for production
cat > /tmp/docker-compose.yml << 'DOCKERCOMPOSE'
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: infrapilot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: infrapilot
      POSTGRES_USER: infrapilot
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U infrapilot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - infrapilot-network

  redis:
    image: redis:7-alpine
    container_name: infrapilot-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - infrapilot-network

  backend:
    image: ghcr.io/venkaiswami/infrapilot-enterprise/backend:latest
    container_name: infrapilot-backend
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - backend_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - infrapilot-network

  frontend:
    image: ghcr.io/venkaiswami/infrapilot-enterprise/frontend:latest
    container_name: infrapilot-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - backend
    networks:
      - infrapilot-network

  nginx:
    image: nginx:alpine
    container_name: infrapilot-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - certbot_data:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - infrapilot-network

volumes:
  postgres_data:
  redis_data:
  backend_logs:
  certbot_data:

networks:
  infrapilot-network:
    driver: bridge
DOCKERCOMPOSE

scp /tmp/docker-compose.yml "${SSH_USER}@${SERVER}:${DEPLOY_DIR}/docker-compose.yml"

# Create nginx config
cat > /tmp/nginx.conf << 'NGINXCONF'
events {
    worker_connections 1024;
}

http {
    server_tokens off;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Rate limiting
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=60r/m;
    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=20r/m;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # HTTP -> HTTPS redirect (if SSL configured)
    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }

    # HTTPS server
    server {
        listen 443 ssl http2;
        server_name _;

        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Frontend
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # API Backend
        location /api/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://backend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # WebSocket
        location /ws {
            proxy_pass http://backend:8080/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 86400;
        }

        # Metrics (restricted to internal)
        location /metrics {
            allow 127.0.0.1;
            deny all;
            proxy_pass http://backend:8080;
        }
    }
}
NGINXCONF

scp /tmp/nginx.conf "${SSH_USER}@${SERVER}:${DEPLOY_DIR}/nginx.conf"

# Create SSL directory with self-signed cert (for initial setup)
ssh "${SSH_USER}@${SERVER}" "mkdir -p ${DEPLOY_DIR}/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout ${DEPLOY_DIR}/ssl/key.pem \
    -out ${DEPLOY_DIR}/ssl/cert.pem \
    -subj '/CN=${DOMAIN}' 2>/dev/null"

echo -e "${GREEN}[5/6]${NC} Starting services..."
ssh "${SSH_USER}@${SERVER}" "cd ${DEPLOY_DIR} && docker compose pull && docker compose up -d"

echo -e "${GREEN}[6/6]${NC} Verifying deployment..."
sleep 10
ssh "${SSH_USER}@${SERVER}" "cd ${DEPLOY_DIR} && docker compose ps && echo '---' && curl -sf http://localhost:8080/healthz && echo 'Health check OK'"

echo ""
echo -e "${CYAN}============================================${NC}"
echo -e "${GREEN}  Deployment Complete!${NC}"
echo -e "${CYAN}============================================${NC}"
echo ""
echo -e "Dashboard:    ${CYAN}http://${DOMAIN}${NC}"
echo -e "API:          ${CYAN}http://${DOMAIN}/api/v1${NC}"
echo -e ""
echo -e "Admin credentials:"
echo -e "  Register at: ${CYAN}http://${DOMAIN}/api/v1/auth/register${NC}"
echo -e ""
echo -e "${YELLOW}Configuration saved to: ${DEPLOY_DIR}/.env${NC}"
echo -e "${YELLOW}Keep this file secure!${NC}"
echo ""
echo -e "For SSL setup with Let's Encrypt:"
echo -e "  sudo certbot --nginx -d ${DOMAIN} --non-interactive --agree-tos -m ${LETSENCRYPT_EMAIL}"
echo ""

# Cleanup local temp files
rm -f /tmp/infrapilot.env /tmp/docker-compose.yml /tmp/nginx.conf