apiVersion: v1
kind: Service
metadata:
  name: infrapilot-redis
  namespace: infrapilot
  labels:
    app: infrapilot-redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: infrapilot-redis